# Пользователи
## Создать нового пользователя

POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "toranssss@overlook.net",
  "author": "Jack",
  "avatar": "torrance.png",
  "status": "Standard",
  "password": "shining"
}

###

## Авторизовать пользователя

POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "toransss@overlook.net",
  "password": "shining"
}

###

## Проверка состояния пользователя.


GET  http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiSmFjayIsImVtYWlsIjoidG9yYW5zc3NAb3Zlcmxvb2submV0IiwiaWQiOiI2NWU4M2U0YWMxOGQ5NjBkZWEzNWE0ZWUiLCJpYXQiOjE3MDk3NTMyNzcsImV4cCI6MTcwOTkyNjA3N30.OefhEtPjHxzwNGYeQsH4BN0D8OJ7UOgdufgF9ztTaIc

###

###

## Добавить в любимый оффер
POST http://localhost:4000/users/favorite-offers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiSmFjayIsImVtYWlsIjoidG9yYW5zc3NAb3Zlcmxvb2submV0IiwiaWQiOiI2NWU4M2U0YWMxOGQ5NjBkZWEzNWE0ZWUiLCJpYXQiOjE3MDk3NDM1NjAsImV4cCI6MTcwOTkxNjM2MH0.7KY8N8cv9yzwS_Osd4A6nmJpq5lQCtOH3k9x5qvKkeU
Content-Type: application/json

{
  "offerId": "65e4a3c4982152359baaad4"
}

###

## Удалить из любимых офферов
DELETE http://localhost:4000/users/favorite-offers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiSmFjayIsImVtYWlsIjoidG9yYW5zc3NAb3Zlcmxvb2submV0IiwiaWQiOiI2NWU4M2U0YWMxOGQ5NjBkZWEzNWE0ZWUiLCJpYXQiOjE3MDk3MTkyMDQsImV4cCI6MTcwOTg5MjAwNH0.NvDKdnb0NwsYzUmoShypr3xq0gsCaPou34jFbwIqNcA
Content-Type: application/json

{
  "offerId": "65e4a3c4982152359baaad4"
}

###
## Отправить изображение

POST http://localhost:4000/users/65e4967a787680a02aaf4956/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="avatar.jpg"
Content-Type: image/jpeg

< /Users/erbetnataly/Desktop/6:03-six-cities-6 2/markup/img/avatar-max.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
