openapi: '3.0.1'
info:
  title: Шесть городов
  summary: API для проекта
  description: Cервис для путешественников, не желающих переплачивать за аренду жилья
  contact:
    name: API Support
    url: https://www.example.com/support
    email: support@example.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.1
servers:
  - url: https://www.example.com/support
    description: Development server
components:
  schemas:   Category:
              type: object



paths:
  /test:
    get:
      responses:
        '200':
          description: OK
